'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = value => value == null ? '—' : Number(value).toLocaleString('zh-CN',{maximumFractionDigits:3});
const state = {catalog:null, data:new Map(), factors:new Map(), analysis:{dataset_ids:[],factor_ids:[],params:{}}, watch:{dataset_ids:[],factor_ids:[],params:{}}, scan:null, result:null, filter:'attention', picker:null, busy:false};
const detailToken = new URLSearchParams(location.search).get('detail');
if(detailToken){document.body.classList.add('detail-window');const style=document.createElement('style');style.textContent='.detail-window .sidebar,.detail-window .topbar,.detail-window #page-monitor,.detail-window #page-analysis>.page-heading,.detail-window .selection-grid,.detail-window .analysis-controls,.detail-window .settings,.detail-window #analysis-status,.detail-window #analysis-metrics,.detail-window #analysis-results,.detail-window #analysis-output>.section-heading,.detail-window footer{display:none!important}.detail-window main{margin:0 auto;padding:32px 40px;max-width:1440px}.detail-window .page{padding:0;min-height:0}.detail-window .detail{margin-top:0}';document.head.append(style);}
function readLocal(key, fallback) {try{return JSON.parse(localStorage.getItem(key)) ?? fallback;}catch{return fallback;}}
function storeLocal(key,value) {try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{showError('浏览器未允许保存本地设置，当前分析仍可使用。');return false;}}
function showError(message='') {$('app-error').textContent=message;$('app-error').hidden=!message;}
async function api(url, payload) {const response=await fetch(url,payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{});const body=await response.json();if(!response.ok){const detail=typeof body.detail==='string'?body.detail:(body.detail||[]).map(x=>x.msg).join('；');throw Error(detail||'请求失败，请稍后重试。');}return body;}
function cleanConfig(config, fallback) {return {dataset_ids:[...new Set((config?.dataset_ids||fallback.dataset_ids).map(x=>state.catalog.dataset_object_ids?.[x]||x))].filter(x=>state.data.has(x)).slice(0,80),factor_ids:(config?.factor_ids||fallback.factor_ids).filter(x=>state.factors.has(x)),params:config?.params||{}};}
function switchPage(page) {document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==`page-${page}`);document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.page===page));$('breadcrumb').textContent='研究工作区 / '+(page==='monitor'?'关注雷达':'手动分析');if(page==='analysis'&&!$('detail').hidden&&window.Plotly)Plotly.Plots.resize('factor-chart');}
function invalidate(scope) {if(scope==='analysis'){$('analysis-status').textContent='选择或参数已修改，请重新运行分析。';$('analysis-output').hidden=true;}else{$('scan-status').textContent='扫描范围或参数已修改，请刷新扫描。';$('scan-results').innerHTML='';$('scan-metrics').innerHTML='';} }
function renderChips() {for(const [kind,element] of [['dataset_ids','selected-data'],['factor_ids','selected-factors']]){const map=kind==='dataset_ids'?state.data:state.factors;$(element).innerHTML=state.analysis[kind].length?state.analysis[kind].map(id=>`<span class="chip" title="${esc(map.get(id)?.source||'')}">${esc(map.get(id)?.name)}<button data-remove="${id}" data-kind="${kind}" aria-label="移除 ${esc(map.get(id)?.name)}">×</button></span>`).join(''):'<span class="muted">点击右上方按钮，从备选条目中添加。</span>';}
  $('watch-summary').textContent=`${state.watch.dataset_ids.length} 个分析对象 · ${state.watch.factor_ids.length} 个因子 · 仅扫描本地已有数据`;
}
function renderParameters(scope) {const config=state[scope];$(scope==='analysis'?'parameters':'watch-parameters').innerHTML=config.factor_ids.map(id=>{const f=state.factors.get(id);return `<div class="parameter-card"><h3>${esc(f.name)}</h3><p>${esc(f.description)}</p><div class="param-inputs">${Object.entries(f.parameters).map(([key,p])=>`<label>${esc(p.label)}<input type="number" min="${p.minimum}" max="${p.maximum}" step="${p.step}" value="${esc(config.params[id]?.[key]??p.default)}" data-param="${key}" data-factor="${id}" data-scope="${scope}" aria-label="${esc(f.name+' '+p.label)}"></label>`).join('')}</div></div>`;}).join('');}
function renderSelection(){renderChips();renderParameters('analysis');renderParameters('watch');}
function openPicker(scope,kind){const config=state[scope];state.picker={scope,kind,chosen:[...config[kind]],visible:[]};$('picker-title').textContent=kind==='dataset_ids'?'选择分析对象':'选择分析因子';$('picker-description').textContent=kind==='dataset_ids'?'按名称、代码或来源搜索，点击 ＋ 移入已选列表。按标的归集全部关联字段，程序自动匹配因子输入，无需逐项勾选价格或成交量。':'选择一个或多个因子。字段不兼容的组合会显示缺少字段，不会补造计算输入。';$('picker-search').value='';const list=kind==='dataset_ids'?[...state.data.values()]:[...state.factors.values()];const categories=[...new Set(list.map(d=>d.category))];$('picker-category').innerHTML='<option value="">全部分类</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('');renderPicker();$('picker').showModal();$('picker-search').focus();}
function pickerRow(item, chosen){const p=state.picker;let detail,compat='';if(p.kind==='dataset_ids'){detail=`${item.category} · ${item.symbol||""} · 最新 ${item.last_date}<br>关联字段：${(item.field_labels||item.fields).join("、")}<br>${item.data_count||1} 组底层数据 · ${item.source}`;}else{detail=`${item.category} · 需要 ${item.required.join(' / ')}<br>${item.description}`;const selected=state[p.scope].dataset_ids.map(id=>state.data.get(id));const count=selected.filter(d=>item.required.every(f=>d.fields.includes(f))&&(!item.dataset_categories||item.dataset_categories.includes(d.category))).length;if(selected.length)compat=`兼容 ${count} / ${selected.length} 个已选对象`;}
return `<div class="pick-row"><div><strong>${esc(item.name)}</strong><p>${detail.split('<br>').map(esc).join('<br>')}</p>${compat?`<p class="compatibility">${compat}</p>`:''}</div><button data-pick-id="${item.id}" data-pick-action="${chosen?'remove':'add'}" aria-label="${chosen?'移除':'添加'} ${esc(item.name)}">${chosen?'−':'＋'}</button></div>`;}
function renderPicker(){const p=state.picker,map=p.kind==='dataset_ids'?state.data:state.factors;const query=$('picker-search').value.trim().toLowerCase(),category=$('picker-category').value;const available=[...map.values()].filter(d=>!p.chosen.includes(d.id)&&(!category||d.category===category)&&[d.name,d.symbol,d.source,d.category,d.id,...(d.field_labels||[])].join(' ').toLowerCase().includes(query));p.visible=available.slice(0,80);$('available-count').textContent=available.length;$('chosen-count').textContent=p.chosen.length;$('available-list').innerHTML=p.visible.map(d=>pickerRow(d,false)).join('')||'<div class="empty">没有匹配的备选条目</div>';$('chosen-list').innerHTML=p.chosen.map(id=>pickerRow(map.get(id),true)).join('')||'<div class="empty">尚未选择<br>从左侧添加条目 →</div>';$('picker-hint').textContent=available.length>80?`共 ${available.length} 条，当前显示前80条；可搜索或分类缩小范围。`:'选择暂存于此，确认后应用。最多选择80个分析对象。';}
function applyPicker(){const p=state.picker;state[p.scope][p.kind]=[...p.chosen];if(p.scope==='watch')storeLocal('quant.watch.v1',state.watch);renderSelection();invalidate(p.scope);$('picker').close();}
function metrics(data,element){const s=data.summary;$(element).innerHTML=[['分析范围',s.datasets,`${s.combinations} 组指标计算`,''],['值得关注',s.attention,'数据未超过新鲜度阈值','attention'],['历史关注',s.historical_attention,'旧数据触发，需更新确认',''],['数据待检查',s.invalid,`${s.stale_datasets} 个对象超过新鲜度阈值`,'']].map(([label,value,note,cls])=>`<div class="metric ${cls}"><label>${label}</label><div class="metric-value">${value}<span style="font-size:11px;font-weight:400;margin-left:8px;color:#9ba4ad">${label==='分析范围'?'个对象':'项'}</span></div><small>${note}</small></div>`).join('');}
function badge(direction){return `<span class="badge ${direction==='偏多'?'bull':direction==='偏空'?'bear':direction==='观察'?'watch':''}">${esc(direction)}</span>`;}
function openDetail(r){const token=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;if(!storeLocal(`quant.detail.${token}`,r))return;const detailWindow=window.open(`${location.pathname}?detail=${encodeURIComponent(token)}`,'_blank');if(!detailWindow){showError('浏览器阻止了详情标签页，请允许本地工作台打开新标签页。');return;}detailWindow.opener=null;}
function resultTable(results,mode){if(!results.length)return '<div class="empty"><strong>本次没有触发关注规则</strong>可以查看全部结果，或调整分析范围与参数。</div>';return `<div class="table-wrap"><table><thead><tr><th>分析对象 / 行情来源</th><th>因子</th><th>最新值</th><th>方向</th><th>状态</th><th>原因</th><th>指标日期</th><th></th></tr></thead><tbody>${results.map(r=>`<tr><td class="name-cell">${esc(r.dataset_name)}<small>${esc(r.source)}</small></td><td>${esc(r.factor_name)}</td><td class="numeric">${fmt(r.value)}</td><td>${badge(r.direction)}</td><td><span class="badge ${r.attention?'watch':''}">${esc(r.status)}</span>${r.stale?'<br><span class="badge stale" style="margin-top:4px">历史状态 · 数据过期</span>':''}</td><td class="reason-cell">${esc(r.reason)}</td><td>${esc(r.value_date||r.data_date||'—')}</td><td><button class="table-button" data-result="${r.dataset_id}" data-result-factor="${r.factor_id}" data-mode="${mode}">${mode==='scan'?'展开分析':'查看详情'} ↗</button></td></tr>`).join('')}</tbody></table></div>`;}
function renderScan(){if(!state.scan)return;if(state.filter==='quality'){$('scan-results').innerHTML=state.scan.issues.map(i=>`<div class="panel quality-item"><h3>${esc(i.name)} ${i.problems.map(x=>`<span class="badge watch">${esc(x)}</span>`).join(' ')}</h3><p>最近数据日期：${esc(i.data_date||'无数据')}</p>${i.notes.map(n=>`<p>· ${esc(n)}</p>`).join('')}</div>`).join('')||'<div class="empty">未发现数据问题。</div>';return;}const rows=state.scan.results.filter(r=>state.filter==='all'||r.attention);$('scan-results').innerHTML=resultTable(rows,'scan');}
function requestBody(scope){const c=state[scope==='monitor'?'watch':scope];if(!c.dataset_ids.length||!c.factor_ids.length)throw Error('请至少选择一个分析对象和一个因子。');const today=state.catalog.today;return {dataset_ids:c.dataset_ids,factors:c.factor_ids.map(id=>({id,params:c.params[id]||{}})),start:scope==='analysis'?$('start-date').value:'2020-01-01',end:scope==='analysis'?$('end-date').value:today,stale_days:Number($('stale-days').value)};}
function setBusy(busy){state.busy=busy;for(const id of ['scan-button','analyze-button','select-data','select-factors','watch-data','watch-factors','watch-reset','preset-select','start-date','end-date','stale-days','save-preset','delete-preset'])$(id).disabled=busy;document.querySelectorAll('[data-param],[data-remove]').forEach(el=>el.disabled=busy);}
async function run(scope){if(state.busy)return;const element=$(scope==='analysis'?'analysis-status':'scan-status');try{showError();const body=requestBody(scope);setBusy(true);element.textContent='正在读取本地行情并计算指标…';element.classList.add('busy');const data=await api(scope==='analysis'?'/api/analyze':'/api/scan',body);if(scope==='analysis'){state.result=data;metrics(data,'analysis-metrics');$('analysis-results').innerHTML=resultTable(data.results,'analysis');$('analysis-output').hidden=false;$('detail').hidden=true;}else{state.scan=data;metrics(data,'scan-metrics');renderScan();}element.textContent=`完成 ${data.summary.combinations} 组计算 · 截止 ${data.end} · ${data.generated_at.replace('T',' ')}${scope==='monitor'?' · 点击刷新扫描可读取最新本地数据':''}`;}catch(e){element.textContent='本次计算未完成';showError(e.message);}finally{setBusy(false);element.classList.remove('busy');}}
let plotlyReady;
function loadPlotly(){if(window.Plotly)return Promise.resolve();if(!plotlyReady)plotlyReady=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/static-plotly.js';script.onload=resolve;script.onerror=()=>{plotlyReady=null;script.remove();reject(Error('图表组件加载失败，请重试。'));};document.head.append(script);});return plotlyReady;}
async function showDetail(r){try{await loadPlotly();}catch(e){showError(e.message);return;}$('detail').hidden=false;$('detail-title').textContent=r.dataset_name+' / '+r.factor_name;$('detail-reason').textContent=r.reason;$('detail-meta').innerHTML=badge(r.direction)+`<span class="badge">${esc(r.status)}</span><span class="badge">数据截至 ${esc(r.data_date||'—')}</span><span class="badge">${esc(Object.entries(r.params).map(([k,v])=>`${k}=${v}`).join(' · '))}</span>`;$('detail-notes').innerHTML=r.notes.map(n=>`<div class="notice">${esc(n)}</div>`).join('');if(r.related_data?.length){$('detail-notes').insertAdjacentHTML('beforeend',`<details class="notice"><summary>关联数据与本次输入（按行情日期对齐；不会把估值、份额当作价格）</summary><div class="table-wrap"><table><thead><tr><th>字段</th><th>最新值</th><th>日期</th><th>单位</th><th>来源</th><th>本因子使用</th></tr></thead><tbody>${r.related_data.map(d=>`<tr><td>${esc(d.label)}</td><td>${fmt(d.value)}</td><td>${esc(d.date||'数据不足')}</td><td>${esc(({CNY:'元',share:'股/份',percent:'%',provider_reported_unverified:'来源单位待核验'})[d.unit]||d.unit||'未注明')}</td><td>${esc(d.source)}</td><td>${d.used?'是':'—'}</td></tr>`).join('')}</tbody></table></div></details>`);}const hist=r.history||[];const dates=hist.map(x=>x.date),f=state.factors.get(r.factor_id);let traces=[];const line=(key,name,color,dash)=>({x:dates,y:hist.map(x=>x[key]),name,type:'scatter',mode:'lines',connectgaps:false,line:{color,width:1.6,dash}});
if(['ma','ema','boll'].includes(r.factor_id)){traces.push(line('input','原始数据','#9aa8b8'));for(const key of r.factor_id==='boll'?['mid','upper','lower']:['value'])traces.push(line(key,r.labels[key]||key,key==='upper'?'#cfa16e':key==='lower'?'#9abbaa':'#277d66',key==='mid'?undefined:key==='value'?undefined:'dot'));}else{traces.push(line('value',r.labels.value||f.name,'#277d66'));if(r.factor_id==='macd')traces.push(line('diff','DIFF','#b48c58'),line('dea','DEA','#8295b3'));if(r.factor_id==='kdj')traces.push(line('d','D','#b48c58'),line('j','J','#8295b3'));}
const divergence = r.factor_id === 'macd_divergence';
if(divergence){
  traces=[line('diff','DIF','#b48c58'),line('dea','DEA','#8295b3'),{x:dates,y:hist.map(row=>row.histogram),name:'MACD柱',type:'bar',marker:{color:hist.map(row=>row.histogram>=0?'#c86965':'#4b967c')}}];
  for(const kind of ['top','bottom']){
    const formed=(r.events||[]).filter(event=>event.state==='formed'&&event.signal_type===kind);
    traces.push({x:formed.map(event=>event.date),y:formed.map(event=>hist.find(row=>row.date===event.date.slice(0,10))?.diff),name:kind==='top'?'顶背离形成':'底背离形成',type:'scatter',mode:'markers',marker:{size:11,symbol:kind==='top'?'triangle-down':'triangle-up',color:kind==='top'?'#b55251':'#256b58'}});
  }
}
const shapes=[];let thresholds=[];if(['rsi','kdj','percentile','vr'].includes(r.factor_id))thresholds=[r.params.lower,r.params.upper];if(['zscore','roc'].includes(r.factor_id))thresholds=[-r.params.threshold,r.params.threshold];if(['volume_ratio','volatility'].includes(r.factor_id))thresholds=[r.params.threshold];for(const y of thresholds)shapes.push({type:'line',xref:'paper',x0:0,x1:1,y0:y,y1:y,line:{color:'#c9b695',width:1,dash:'dot'}});
const hasPrice=hist.some(row=>Number.isFinite(row.input));
const priceName=r.price_chart?.is_price===false?'原始数据':'收盘价';
const axis={showgrid:false,rangeslider:{visible:false},showspikes:true,spikemode:'across',spikesnap:'cursor',spikecolor:'#607080',spikethickness:1,spikedash:'dot'};
for(const trace of traces){trace.xaxis='x2';trace.yaxis='y2';}
for(const shape of shapes){shape.yref='y2';}
if(hasPrice)traces.unshift({type:'scatter',mode:'lines',name:priceName,x:dates,y:hist.map(row=>row.input),xaxis:'x',yaxis:'y',connectgaps:false,line:{color:'#387f72',width:1.8},hovertemplate:`${priceName}: %{y:,.3f}<extra></extra>`});
const chartLayout={margin:{l:65,r:65,t:54,b:45},paper_bgcolor:'#fff',plot_bgcolor:'#fff',font:{family:'Segoe UI, Microsoft YaHei',size:11,color:'#7d8895'},xaxis:{...axis,domain:[0,1],anchor:'y',showticklabels:false},yaxis:{domain:hasPrice?[0.42,1]:[0,1],gridcolor:'#edf1f4',zerolinecolor:'#dfe5e9',title:{text:hasPrice?priceName:'数值'}},xaxis2:{...axis,domain:[0,1],anchor:'y2',matches:'x',title:{text:'日期'}},yaxis2:{domain:hasPrice?[0,0.30]:[0,1],gridcolor:'#edf1f4',zerolinecolor:'#dfe5e9',title:{text:hasPrice?'因子':'数值'}},legend:{orientation:'h',y:1.09},hovermode:'x unified',hoversubplots:'axis',hoverlabel:{bgcolor:'#ffffff',bordercolor:'#d8e0e6',font:{color:'#253244'}},shapes};
const graph=$('factor-chart');
graph.style.height=hasPrice?'580px':'500px';
graph.removeAllListeners?.('plotly_hover');
graph.removeAllListeners?.('plotly_unhover');
await Plotly.react(graph,traces,chartLayout,{responsive:true,displaylogo:false,modeBarButtonsToRemove:['select2d','lasso2d']});
let hoveredX=null;
const baseShapes=chartLayout.shapes;
const cursorShape=x=>({type:'line',xref:'x',yref:'paper',x0:x,x1:x,y0:0,y1:1,line:{color:'#607080',width:1,dash:'dot'},layer:'above'});
graph.on('plotly_hover',event=>{const x=event.points?.[0]?.x;if(x==null||x===hoveredX)return;hoveredX=x;Plotly.relayout(graph,{shapes:[...baseShapes,cursorShape(x)]});});
graph.on('plotly_unhover',()=>{if(hoveredX==null)return;hoveredX=null;Plotly.relayout(graph,{shapes:baseShapes});});

const events=[...(r.events||[])].reverse();
$('events-count').textContent=`共 ${events.length} 条${divergence?'状态转移':'触发记录'}`;
const transitionNames={started:'开始',formed:'形成',invalidated:'失效'};
$('detail-events').innerHTML=events.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>方向</th>${divergence?'<th>状态</th><th>比较</th><th>价格极值 / 日期</th><th>DIF极值 / 日期</th><th>比较价格 / DIF</th>':''}<th>原因</th></tr></thead><tbody>${events.map(event=>`<tr><td>${esc(event.date)}</td><td>${badge(event.direction)}</td>${divergence?`<td>${esc(transitionNames[event.state])}</td><td>${event.wave_distance===1?'邻峰':'隔峰'} #${esc(event.compare_wave_id)}</td><td>${fmt(event.price_value)} / ${esc(event.price_anchor_time)}</td><td>${fmt(event.dif_value)} / ${esc(event.dif_anchor_time)}</td><td>${fmt(event.compare_price)} / ${fmt(event.compare_dif)}</td>`:''}<td>${esc(event.reason)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">所选区间内没有触发关注阈值。</p>';
if(divergence){
  const exportButton=document.createElement('button');exportButton.textContent='导出完整背离状态记录 JSON';exportButton.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({signals:r.signals,transitions:r.events},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='MACD背离状态.json';link.click();URL.revokeObjectURL(url);};$('detail-events').prepend(exportButton);
}
$('detail').scrollIntoView({behavior:'smooth',block:'start'});}
function refreshPresets(){const presets=readLocal('quant.presets.v1',{});$('preset-select').innerHTML='<option value="">载入分析方案…</option>'+Object.keys(presets).map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');}
function downloadResults(){if(!state.result)return;const headers=['数据','因子','数值','方向','状态','原因','数据日期','指标日期','分析截止日','数据过期','来源','参数'];const rows=state.result.results.map(r=>[r.dataset_name,r.factor_name,r.value,r.direction,r.status,r.reason,r.data_date,r.value_date,r.as_of,r.stale,r.source,JSON.stringify(r.params)]);const cell=v=>{let s=String(v??'');if(/^[=+@-]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const blob=new Blob(['\uFEFF'+[headers,...rows].map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Quant分析_${state.result.end}.csv`;a.click();URL.revokeObjectURL(url);}
document.addEventListener('click',async event=>{const nav=event.target.closest('[data-page]');if(nav)switchPage(nav.dataset.page);const remove=event.target.closest('[data-remove]');if(remove&&!state.busy){state.analysis[remove.dataset.kind]=state.analysis[remove.dataset.kind].filter(x=>x!==remove.dataset.remove);renderSelection();invalidate('analysis');}const pick=event.target.closest('[data-pick-id]');if(pick){const p=state.picker,id=pick.dataset.pickId;if(pick.dataset.pickAction==='remove')p.chosen=p.chosen.filter(x=>x!==id);else if(!p.chosen.includes(id)&&(p.kind!=='dataset_ids'||p.chosen.length<80))p.chosen.push(id);renderPicker();}const filter=event.target.closest('[data-filter]');if(filter){state.filter=filter.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('selected',el===filter));renderScan();}const result=event.target.closest('[data-result]');if(result&&!state.busy){const source=result.dataset.mode==='scan'?state.scan:state.result;const r=source.results.find(x=>x.dataset_id===result.dataset.result&&x.factor_id===result.dataset.resultFactor);if(result.dataset.mode==='scan'){state.analysis={dataset_ids:[r.dataset_id],factor_ids:[r.factor_id],params:{[r.factor_id]:r.params}};renderSelection();switchPage('analysis');await run('analysis');if(state.result?.results[0]?.dataset_id===r.dataset_id)openDetail(state.result.results[0]);}else openDetail(r);}});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.param){const c=state[el.dataset.scope];c.params[el.dataset.factor]??={};c.params[el.dataset.factor][el.dataset.param]=Number(el.value);invalidate(el.dataset.scope);if(el.dataset.scope==='watch')storeLocal('quant.watch.v1',state.watch);}if(['start-date','end-date'].includes(el.id))invalidate('analysis');if(el.id==='stale-days'){invalidate('watch');invalidate('analysis');}});
$('select-data').onclick=()=>openPicker('analysis','dataset_ids');$('select-factors').onclick=()=>openPicker('analysis','factor_ids');$('watch-data').onclick=()=>openPicker('watch','dataset_ids');$('watch-factors').onclick=()=>openPicker('watch','factor_ids');$('picker-search').oninput=renderPicker;$('picker-category').onchange=renderPicker;for(const id of ['picker-close','picker-cancel'])$(id).onclick=()=>$('picker').close();$('picker-apply').onclick=applyPicker;$('clear-chosen').onclick=()=>{state.picker.chosen=[];renderPicker();};$('add-visible').onclick=()=>{const p=state.picker;for(const d of p.visible){if(p.kind==='dataset_ids'&&p.chosen.length>=80)break;p.chosen.push(d.id);}renderPicker();};$('scan-button').onclick=()=>run('monitor');$('analyze-button').onclick=()=>run('analysis');$('detail-close').onclick=()=>{if(detailToken)window.close();else $('detail').hidden=true;};$('download-results').onclick=downloadResults;
$('watch-reset').onclick=async()=>{try{const defaults=await api('/api/scan-defaults');state.watch=cleanConfig(null,{dataset_ids:defaults.dataset_ids,factor_ids:defaults.factors.map(f=>f.id)});storeLocal('quant.watch.v1',state.watch);renderSelection();invalidate('watch');}catch(e){showError(e.message);}};
$('divergence-preset').onclick=async()=>{if(state.busy)return;try{state.watch=cleanConfig(await api('/api/divergence-defaults'),state.catalog.defaults);storeLocal('quant.watch.v1',state.watch);renderSelection();invalidate('watch');await run('monitor');}catch(error){showError(error.message);}};
$('save-preset').onclick=()=>{$('preset-name').value='';$('save-message').textContent='';$('save-dialog').showModal();$('preset-name').focus();};$('save-cancel').onclick=()=>$('save-dialog').close();$('save-confirm').onclick=()=>{const name=$('preset-name').value.trim();if(!name){$('save-message').textContent='请输入方案名称';return;}const presets=readLocal('quant.presets.v1',{});if(Object.hasOwn(presets,name)){$('save-message').textContent='名称已存在，请使用新名称';return;}Object.defineProperty(presets,name,{value:{...state.analysis,start:$('start-date').value,end:$('end-date').value},enumerable:true,configurable:true});if(storeLocal('quant.presets.v1',presets)){refreshPresets();$('save-dialog').close();}};
$('preset-select').onchange=()=>{const p=readLocal('quant.presets.v1',{})[$('preset-select').value];if(!p)return;state.analysis=cleanConfig(p,state.catalog.defaults);$('start-date').value=p.start;$('end-date').value=p.end;renderSelection();invalidate('analysis');};$('delete-preset').onclick=()=>{const name=$('preset-select').value;if(!name)return;const presets=readLocal('quant.presets.v1',{});delete presets[name];storeLocal('quant.presets.v1',presets);refreshPresets();};
async function init(){try{setBusy(true);const catalog=await api('/api/catalog');state.catalog=catalog;publishedGeneration=catalog.snapshot;state.data=new Map(catalog.objects.map(d=>[d.id,d]));state.factors=new Map(catalog.factors.map(f=>[f.id,f]));state.analysis=cleanConfig(null,catalog.defaults);const defaults=await api('/api/scan-defaults');state.watch=cleanConfig(readLocal('quant.watch.v1',null),{dataset_ids:defaults.dataset_ids,factor_ids:defaults.factors.map(f=>f.id)});$('start-date').value=`${Number(catalog.today.slice(0,4))-1}${catalog.today.slice(4)}`;$('end-date').value=catalog.today;$('end-date').max=catalog.today;$('database-note').textContent=`${catalog.objects.length.toLocaleString()} 个分析对象 · ${catalog.datasets.length.toLocaleString()} 组底层数据 · ${catalog.factors.length} 个因子\n交易日历至 ${catalog.calendar_until||'未知'}`;renderSelection();refreshPresets();setBusy(false);if(detailToken){const detail=readLocal(`quant.detail.${detailToken}`,null);if(!detail)throw Error('该详情页已失效，请回到分析结果重新打开。');switchPage('analysis');$('analysis-output').hidden=false;document.title=`${detail.dataset_name} / ${detail.factor_name} · Quant`;await showDetail(detail);return;}await run('monitor');}catch(e){showError(e.message);$('scan-status').textContent='目录加载失败，请刷新页面重试。';setBusy(false);}}
if(location.protocol==='file:'){showError('这是页面文件预览，分析需要本地服务。请运行工程中的 Quant.bat，然后打开 http://127.0.0.1:8600 。');$('scan-status').innerHTML='<a href="http://127.0.0.1:8600">打开 Quant 分析工作台 →</a>';$('database-note').textContent='尚未连接本地分析服务';$('watch-summary').textContent='请通过本地服务打开工作台';setBusy(true);}else{init();}

// Updates publish a new immutable generation without stopping the API.
let publishedGeneration = null;
let statusPolling = false;
async function pollDataStatus() {
  if (statusPolling || state.busy || !state.catalog) return;
  statusPolling = true;
  try {
    const status = await api('/api/data-status');
    let note = document.getElementById('sync-note');
    if (!note) { note = document.createElement('div'); note.id = 'sync-note'; $('database-note').after(note); }
    note.textContent = status.status === 'running'
      ? `数据正在更新（${status.stage || '获取'}）；当前继续提供已发布数据。`
      : `数据发布于 ${status.published_at ? new Date(status.published_at).toLocaleString() : '未知'}${status.status === 'partial' ? '；部分数据仍有缺口，详见更新报告。' : status.status === 'failed' ? '；最近更新失败，继续提供上一版。' : ''}`;
    if (publishedGeneration && status.snapshot && publishedGeneration !== status.snapshot) {
      const catalog = await api('/api/catalog');
      state.catalog = catalog;
      state.data = new Map(catalog.objects.map(d => [d.id, d]));
      state.factors = new Map(catalog.factors.map(f => [f.id, f]));
      state.analysis = cleanConfig(state.analysis, catalog.defaults);
      state.watch = cleanConfig(state.watch, catalog.defaults);
      renderSelection();
      invalidate('analysis'); invalidate('watch');
      await run('monitor');
    }
    publishedGeneration = status.snapshot;
  } catch (error) {
    const note = document.getElementById('sync-note');
    if (note) note.textContent = '暂时无法获取更新状态，稍后自动重试。';
  } finally { statusPolling = false; }
}
if (location.protocol !== 'file:') setInterval(pollDataStatus, 5000);

